export const BOOKING_PLATFORM_FEE_RATE = 0.1;
export const BOOKING_DAMAGE_WAIVER_FEE = 999;
export const BOOKING_SECURITY_DEPOSIT_RATE = 0.3;
export const BOOKING_SECURITY_DEPOSIT_MIN = 500;
export const BOOKING_SECURITY_DEPOSIT_MAX = 5000;
export const BOOKING_PAYMENT_PROVIDER = "RAZORPAY_PLATFORM_COLLECTION";
export const BOOKING_OWNER_APPROVAL_WINDOW_HOURS = 24;
export const BOOKING_RENTER_PAYMENT_WINDOW_HOURS = 1;
